# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('being_unknown', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('addressed_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('picture_path', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('summary_len', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('IMPORTANT', 'Important')], default='NORMAL', max_length=15)),
                ('is_public', models.BooleanField(default=True)),
                ('being_unknown', models.BooleanField(default=False)),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROGRESSING', 'Progressing'), ('SOLVED', 'Solved'), ('CLOSED', 'Closed')], default='PENDING', max_length=15)),
                ('need_to_confirmed', models.BooleanField(default=False)),
                ('minimum_approvers_count', models.IntegerField(default=0)),
                ('addressed_users', models.ManyToManyField(related_name='ticket_M2M_addressed_users', to=settings.AUTH_USER_MODEL)),
                ('cc_users', models.ManyToManyField(blank=True, related_name='ticket_M2M_cc_users', to=settings.AUTH_USER_MODEL)),
                ('contributers', models.ManyToManyField(related_name='ticket_M2M_contributers', to=settings.AUTH_USER_MODEL)),
                ('in_list_contributers', models.ManyToManyField(blank=True, related_name='ticket_M2M_in_list_contributers', to=settings.AUTH_USER_MODEL)),
                ('known_approvers', models.ManyToManyField(blank=True, related_name='ticket_M2M_known_approvers', to=settings.AUTH_USER_MODEL)),
                ('known_denials', models.ManyToManyField(blank=True, related_name='ticket_M2M_known_denials', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Ticket')),
                ('tag_list', models.ManyToManyField(blank=True, to='ticket_service.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('department', models.ManyToManyField(to='ticket_service.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeStatus',
            fields=[
                ('activities_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_service.Activities')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROGRESSING', 'Progressing'), ('SOLVED', 'Solved'), ('CLOSED', 'Closed')], max_length=15)),
            ],
            bases=('ticket_service.activities',),
        ),
        migrations.CreateModel(
            name='edit',
            fields=[
                ('activities_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_service.Activities')),
                ('new_body', models.TextField()),
                ('new_title', models.CharField(max_length=500)),
            ],
            bases=('ticket_service.activities',),
        ),
        migrations.CreateModel(
            name='PrivateAttachments',
            fields=[
                ('baseattachments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_service.BaseAttachments')),
            ],
            bases=('ticket_service.baseattachments',),
        ),
        migrations.CreateModel(
            name='PublicAttachments',
            fields=[
                ('baseattachments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_service.BaseAttachments')),
            ],
            bases=('ticket_service.baseattachments',),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('activities_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_service.Activities')),
                ('reffered_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('ticket_service.activities',),
        ),
        migrations.CreateModel(
            name='Reopen',
            fields=[
                ('activities_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_service.Activities')),
            ],
            bases=('ticket_service.activities',),
        ),
        migrations.CreateModel(
            name='SetConfirmationLimit',
            fields=[
                ('activities_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_service.Activities')),
                ('limit_value', models.IntegerField(default=0)),
                ('need_to_confirmed', models.BooleanField(default=False)),
            ],
            bases=('ticket_service.activities',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unknown_approvers',
            field=models.ManyToManyField(blank=True, related_name='ticket_M2M_unknown_approvers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unknown_denials',
            field=models.ManyToManyField(blank=True, related_name='ticket_M2M_unknown_denials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateticket',
            name='parent_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Ticket'),
        ),
        migrations.AddField(
            model_name='comments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Ticket'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activities',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Ticket'),
        ),
        migrations.AddField(
            model_name='activities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reopen',
            name='new_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Ticket'),
        ),
        migrations.AddField(
            model_name='publicattachments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_service.Ticket'),
        ),
        migrations.AddField(
            model_name='privateattachments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_service.PrivateTicket'),
        ),
    ]
